name: Release latest

on:
  push:
    branches:
      - main

jobs:
  container-push-latest:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: yaml-toolbox
      tag: latest
      dockerfile_path: images/Dockerfile